### ISSUE TITLE
Welcome - 也无风雨也无晴

### ISSUE THREAD

**Issue by scutLMG** [scutLMG/blog_comment#14]
https://scutlmg.github.io/2020/06/30/welcome/ 

 欢迎访问戴闻濠的博客。还没想好写什么，不过可以随时改，先这样吧。

**Comment by JIeJaitt** [comment]
博主你顶部导航栏怎么固定的？

**Comment by scutLMG** [comment]
在 hexo-theme-icarus\source\css\style.styl 内添加
```
.navbar
 z-index: 100
 position: sticky
 top: 0
```

详见[本博客文章](https://scutlmg.github.io/2021/10/09/hexo%E5%8D%9A%E5%AE%A2%E6%94%B9%E8%BF%9B%E8%AE%B0%E5%BD%95/#%E5%9B%BA%E5%AE%9A%E5%AF%BC%E8%88%AA%E6%A0%8F)

**Comment by scutLMG** [comment]
> 博主你顶部导航栏怎么固定的？

在 hexo-theme-icarus\source\css\style.styl 内添加

```
.navbar
 z-index: 100
 position: sticky
 top: 0

```
详见[本博客文章](https://scutlmg.github.io/2021/10/09/hexo%E5%8D%9A%E5%AE%A2%E6%94%B9%E8%BF%9B%E8%AE%B0%E5%BD%95/#%E5%9B%BA%E5%AE%9A%E5%AF%BC%E8%88%AA%E6%A0%8F)
